CREATE TABLE IF NOT EXISTS last_news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title_ar VARCHAR(255) NOT NULL,
  content_ar TEXT NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  is_active TINYINT(1) DEFAULT 1,
  priority INT DEFAULT 0,
  views INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);